### ISSUE TITLE
Unable to decrypt files

### ISSUE THREAD

**Issue by joaomorenorf** [eblocha/django-encrypted-files#2]
Hello!

We changed the `FILE_UPLOAD_HANDLERS` as advised and the files inside the file system seems to be encrypted correctly. They are almost the same size, but a little bit bigger.

 We tried to use this line in the file return method, and it didn't worked.
 ```
return FileResponse(EncryptedFile(open(os.path.join(Path(__file__).resolve().parent.parent, file[1:]), 'rb')))
```

How should we implement the decryption method?

## Can you provide a way to test encryption outside your package?
I tried to use openssl, but with no luck.

```
$ python3
>>> AES_KEY = b'\x1a>\xf8\xcd\xe2\x8e_~V\x14\x98\xc2\x1f\xf9\xea\xf8\xd7c\xb3`!d\xd4\xe3+\xf7Q\x83\xb5~\x8f\xdd'
>>> AES_KEY.hex()
'1a3ef8cde28e5f7e561498c21ff9eaf8d763b3602164d4e32bf75183b57e8fdd'
>>> full = open ("encrypted-raw.png", 'rb')
>>> save=open("encrypted.png", "wb")
>>> read = full.read()
>>> save.write(read[16:])
>>> read[:16].hex()
'6907a8ed41042e63a7b6855258116f9b'
>>> exit()
$ openssl enc -d -aes-256-cbc -K "1a3ef8cde28e5f7e561498c21ff9eaf8d763b3602164d4e32bf75183b57e8fdd" -iv 6907a8ed41042e63a7b6855258116f9b -in encrypted.png -out decrypted.png
bad decrypt
140061768324480:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
```

**Comment by eblocha** [comment]
Hi @joaomorenorf

It seems you are passing a list to `os.path.join` when you pass in `file[1:]`. Also I believe the `Path(__file__).resolve().parent.parent` is a `Path` object, and not `str`. Could that be the issue?

For decrypting with openssl, use CTR mode instead of CBC. I have not tested decryption with openssl, but you can also use the python `cryptography` library, which is what this package is using under the hood for encryption/decryption. You may also have to zero-pad the encrypted file, as it mentions `wrong final block length`.

**Comment by Gabriel-Rezende** [comment]
Hi, @eblocha.

I'm from João's team.

Our variable file is a string to our media folder, containg our file. Replacing it by a example file, we would have something like:

`return FileResponse(open(os.path.join('media/uploads/2022/01/25/lista_redes.pdf'), 'rb'))`

This works fine, we used that before, but we wanted to integrate it with your django-encrypted-file. 

Even using the suggested method to decrypt a file:

`
def decrypted(request,pk):
    f = ModelWithFile.objects.get(pk=pk).file
    ef = EncryptedFile(f)
    return HttpResponse(ef.read())
`

The HttpResponse returns


![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/49629009/151193288-26616e05-f8b2-46b1-a156-0916be24617b.png)

We have a model called "Anexo" that contains a FileField called "arquivo". Replacing the example code exactly as suggested, but with our Anexo.objects.get(pk=pk).arquivo instead of yours ModelWithFile example.

**Comment by eblocha** [comment]
Hi @Gabriel-Rezende, I know this issue is old, but I think this may be due to an incorrect MIME type. It looks like the file is decrypting properly based on the `PNG` in the response data.

The example is intended for text-based files, since HttpResponse defaults to "text/plain" MIME if none is specified. With FileResponse, it looks like it tries to use either the "name" property on the file-like object (which EncryptedFile does not implement, it inherits from Django's `File` object). Or, it will use a `filename` argument passed to it. If both fail, it falls back to "application/octet-stream".

You can try passing the `filename` attribute to `FileResponse`.

https://docs.djangoproject.com/en/4.0/ref/request-response/#fileresponse-objects

I will update the readme to include a note about the example.

**Comment by Gabriel-Rezende** [comment]
That's it! Thanks for the suggestion.
