### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by gishamohebi** [eblocha/django-encrypted-files#4]
Hello, can you help me please?
I encrypted a csv file and decrypted it with this package. When I pass ef (decode file) to numpy.loadtxt it gives me a conversion value error : "Could not convert string to float".
It looks like it can't read the file properly.
I even gave the skiprows and usecols to the function.
However it works before encrypting the data.
Do you have any ideas?
Thank you

**Comment by eblocha** [comment]
Hi @gishamohebi, how did you encrypt the file? The EncryptedFile object expects a 16-byte nonce at the beginning of the file, and offsets the file data to account for it. If the nonce is not present, it will attempt use whatever the first 16 bytes are, which won't go very well. You'll just get random-looking bytes from `.read()`.

Additionally, the data must be encrypted with AES in CTR mode.

**Comment by gishamohebi** [comment]
Thanks for the reply @eblocha. I did the encryption process as you said through the document. File is perfectly decrypted . The problem is that numpy.loadtxt doesn't read it well. It reads the file with its \r\n parameters. I was wondering if this is related to the encrypting type for a csv file. I checked pandas.read_csv and passed "ef" to it and it was fine reading it.

**Comment by eblocha** [comment]
Good to see that it decrypts properly @gishamohebi. My suspicion is that `numpy.loadtxt` doesn't like the way `EncryptedFile` iterates over the file data. It reads a number of bytes defined by `DEFAULT_CHUNK_SIZE` as a class property (inherited from Django's `File` object). `nupmy.loadtxt` seems to expect a generator-like object to emit lines, not a constant-size chunk of raw bytes.

The example given using StringIO by the [numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy-loadtxt) works because StringIO will emit lines when used as a generator.

```
Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> s = io.StringIO("first line\nsecond line")
>>> x = [l for l in s]
>>> x
['first line\n', 'second line']
>>> 
```

So, I think you will either need to wrap the `EncryptedFile` class in a function that acts as a generator for lines. Or, if memory is not as much of a concern, you could read the entire encrypted file into a StringIO buffer, then pass that to `numpy.loadtxt`.

**Comment by gishamohebi** [comment]
You are right. Thank you for your suggestion and time. I just used pandas and it works great.
